Repository psalm/psalm-plugin-laravel, pull requests merged in 2020-07, with the labels that each got.

#92 fixing conflict issue in composer requirements
  composer.json
Labels: fix

#95 test: add a test for resource and wrap
  tests/acceptance/HttpResourceTypes.feature
Labels: chore

#100 feature: abort_if support
  composer.json
  src/Stubs/helpers.stubphp
  tests/acceptance/AbortIf.feature
Labels: enhancement

#102 change: resolve abstracts from container. This will allow us to resolve named aliases
  src/AppInterfaceProvider.php
  src/ContainerResolver.php
  src/ReturnTypeProvider/AppReturnTypeProvider.php
  src/Stubs/Application.stubphp
  tests/acceptance/Container.feature
Labels: enhancement

#104 test: add test for app env
  tests/acceptance/Helpers.feature
Labels: chore, enhancement
