Repository psalm/psalm-plugin-laravel, pull requests merged in 2021-07, with the labels that each got.

#126 DB facade alias support
  stubs/DBFacade.stubphp
  tests/acceptance/DBFacadeAlias.feature
Labels: fix

#163 feature: proper return types for logger. closes #161
  stubs/helpers.stubphp
  tests/acceptance/Helpers.feature
Labels: enhancement

#164 chore(gitignore): add laravel folder
  .gitignore
Labels: chore

#169 Reword acceptance tests
  tests/acceptance/AbortIf.feature
  tests/acceptance/CollectionTypes.feature
  tests/acceptance/Container.feature
  tests/acceptance/DBFacadeAlias.feature
  tests/acceptance/DatabaseBuilderTypes.feature
  tests/acceptance/EloquentBuilderTypes.feature
  tests/acceptance/EloquentCollectionTypes.feature
  tests/acceptance/EloquentModelTypes.feature
  tests/acceptance/EloquentRelationTypes.feature
  tests/acceptance/FactoryTypes.feature
  tests/acceptance/HttpResourceTypes.feature
  tests/acceptance/PathHelpers.feature
  tests/acceptance/RedirectReturnType.feature
  tests/acceptance/RequestTypes.feature
  tests/acceptance/ResponseReturnType.feature
  tests/acceptance/TaintAnalysis.feature
  tests/acceptance/UrlReturnType.feature
Labels: chore

#171 test: add test case for abort()
  tests/acceptance/AbortIf.feature
Labels: chore

#174 chore: optimize + add imports
  src/Fakes/FakeFilesystem.php
  src/Fakes/FakeMetaCommand.php
  src/Fakes/FakeModelsCommand.php
  src/Handlers/Application/ContainerHandler.php
  src/Handlers/Eloquent/ModelMethodHandler.php
  src/Handlers/Eloquent/ModelPropertyAccessorHandler.php
  src/Handlers/Eloquent/ModelRelationshipPropertyHandler.php
  src/Handlers/Eloquent/RelationsMethodHandler.php
  src/Handlers/Eloquent/Schema/SchemaAggregator.php
  src/Handlers/Helpers/PathHandler.php
  src/Handlers/Helpers/TransHandler.php
  src/Handlers/Helpers/ViewHandler.php
  src/Plugin.php
  src/Providers/ApplicationProvider.php
  src/Providers/FacadeStubProvider.php
  src/Providers/ModelStubProvider.php
  src/Providers/ViewFactoryProvider.php
  src/Stubs/Optional.stubphp
  src/Util/ContainerResolver.php
  src/Util/ProxyMethodReturnTypeProvider.php
  tests/Models/Image.php
Labels: chore

#176 Test Laravel 6.x (LTS) instead of 7.x (EOL)
  .github/workflows/test.yml
Labels: chore

#177 fix: add missing illuminate/* dependencies
  composer.json
Labels: chore

#172 fix: ignore PropertyNotSetInConstructor in Console\Command, Http\FormRequest and Notifications\Notifications classes
  src/Handlers/SuppressHandler.php
  src/Plugin.php
  tests/acceptance/ConsoleCommand.feature
  tests/acceptance/HttpFormRequest.feature
  tests/acceptance/Notification.feature
Labels: enhancement

#170 fix: Support @property on Model with imported type
  src/Providers/ModelStubProvider.php
  tests/Models/AbstractUuidModel.php
  tests/Models/Secret.php
  tests/Models/User.php
  tests/acceptance/EloquentModelPropertyTypes.feature
Labels: fix

#178 Migrate from Psalm Hooks to EventHandlers
  src/Fakes/FakeModelsCommand.php
  src/Handlers/Application/ContainerHandler.php
  src/Handlers/Eloquent/ModelMethodHandler.php
  src/Handlers/Eloquent/ModelPropertyAccessorHandler.php
  src/Handlers/Eloquent/ModelRelationshipPropertyHandler.php
  src/Handlers/Eloquent/RelationsMethodHandler.php
  src/Handlers/Helpers/PathHandler.php
  src/Handlers/Helpers/RedirectHandler.php
  src/Handlers/Helpers/TransHandler.php
  src/Handlers/Helpers/UrlHandler.php
  src/Handlers/Helpers/ViewHandler.php
  src/Plugin.php
  src/Providers/ViewFactoryProvider.php
  src/Util/ProxyMethodReturnTypeProvider.php
Labels: chore

#181 test(Notification): run only for Laravel 6.0.4+
  tests/acceptance/Notification.feature
Labels: chore

#182 Ensure factory() helper is gone in Laravel 8+
  src/Plugin.php
  stubs/6/helpers.stubphp
  stubs/7/helpers.stubphp
  stubs/helpers.stubphp
  tests/acceptance/FactoryTypes.feature
Labels: enhancement

#183 Suppress UnusedClass/PossiblyUnusedMethod on well-known classes/methods of fresh Laravel/Lumen projects
  src/Handlers/SuppressHandler.php
  tests/laravel-test-baseline.xml
  tests/laravel-test-psalm.xml
  tests/lumen-test-baseline.xml
  tests/lumen-test-psalm.xml
Labels: enhancement

#185 Drop support for Laravel 7
  composer.json
  stubs/7/helpers.stubphp
  tests/acceptance/FactoryTypes.feature
Labels: change

#157 Ensure firstOrNew/Create can be called without parameters in Laravel 8+
  stubs/6/EloquentBuilder.stubphp
  stubs/6/HasOneOrMany.stubphp
  stubs/8/EloquentBuilder.stubphp
  stubs/8/HasOneOrMany.stubphp
  stubs/EloquentBuilder.stubphp
  stubs/HasOneOrMany.stubphp
  tests/acceptance/EloquentBuilderTypes.feature
  tests/acceptance/EloquentRelationTypes.feature
Labels: fix

#188 Fix database migrations path
  src/Providers/ModelStubProvider.php
Labels: fix

#189 test(laravel): run make:* commands
  src/Handlers/SuppressHandler.php
  tests/laravel-test-baseline.xml
  tests/laravel-test.sh
Labels: enhancement
