Repository psalm/psalm-plugin-laravel, pull requests merged in 2021-06, with the labels that each got.

#136 Update method signature for getPropertiesFromTable
  composer.json
  src/FakeModelsCommand.php
Labels: fix

#148 fix(lint): run phpcs with php 7.4
  .github/workflows/lint.yml
Labels: chore

#150 Add missing schema declaration
  src/SchemaAggregator.php
Labels: enhancement

#159 feature: support for morphOne
  stubs/MorphOne.stubphp
Labels: fix
