Repository psalm/psalm-plugin-laravel, pull requests merged in 2023-11, with the labels that each got.

#352 Fix tests for path helpers
  tests/Acceptance/acceptance/PathHelpers.feature
Labels: release:fix

#354 Fix ArgumentTypeCoercion issue
  src/Handlers/Eloquent/ModelMethodHandler.php
  src/Handlers/Eloquent/ModelPropertyAccessorHandler.php
Labels: release:skip-changelog

#355 Run test suite with PHP 8.3
  .github/workflows/psalm.yml
  .github/workflows/test-laravel.yml
  .github/workflows/test.yml
Labels: release:internal

#350 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: release:skip-changelog

#357 Display "The package is seeking maintainers" message
  README.md
Labels: release:skip-changelog

#356 Reorganize stubs by directories
  src/Plugin.php
  stubs/Database/Eloquent/Collection.stubphp
  stubs/Database/Eloquent/Concerns/HasRelationships.stubphp
  stubs/Database/Eloquent/Concerns/ManagesTransactions.stubphp
  stubs/Database/Eloquent/Relations/BelongsTo.stubphp
  stubs/Database/Eloquent/Relations/BelongsToMany.stubphp
  stubs/Database/Eloquent/Relations/HasMany.stubphp
  stubs/Database/Eloquent/Relations/HasManyThrough.stubphp
  stubs/Database/Eloquent/Relations/HasOne.stubphp
  stubs/Database/Eloquent/Relations/HasOneOrMany.stubphp
  stubs/Database/Eloquent/Relations/HasOneThrough.stubphp
  stubs/Database/Eloquent/Relations/MorphMany.stubphp
  stubs/Database/Eloquent/Relations/MorphOne.stubphp
  stubs/Database/Eloquent/Relations/MorphOneOrMany.stubphp
  stubs/Database/Eloquent/Relations/MorphToMany.stubphp
  stubs/Database/Eloquent/Relations/Relation.stubphp
  stubs/Database/Query/Builder.stubphp
Labels: release:skip-changelog

#360 Remove failing test to make CI green again (temp solution)
  tests/Acceptance/acceptance/EloquentCollectionTypes.feature
Labels: release:internal, release:skip-changelog
