Repository psalm/psalm-plugin-laravel, pull requests merged in 2023-01, with the labels that each got.

#259 Adjust release-drafter config (use psalm-like setup)
  .github/config/release-drafter.yml
Labels: release:internal

#256 Update codeception module for plugin
  phpcs.xml
  src/Fakes/FakeModelsCommandLogic.php
  tests/Support/Module.php
Labels: chore, release:patch

#263 Allow to auto-exclude PRs from release notes (based on a label)
  .github/config/release-drafter.yml
Labels: release:skip-changelog

#264 Remove stale code created to support outdated version of ide-helper
  psalm.xml
  src/Fakes/FakeModelsCommand.php
  src/Fakes/FakeModelsCommand210.php
  src/Fakes/FakeModelsCommand291.php
  src/Providers/FakeModelsCommandProvider.php
  src/Providers/ModelStubProvider.php
Labels: chore

#266 Remove dead code
  composer.json
  psalm.xml
  src/Fakes/FakeMetaCommand.php
  src/Handlers/Eloquent/Schema/SchemaAggregator.php
  src/Handlers/Eloquent/Schema/SchemaTable.php
  src/Providers/ApplicationProvider.php
Labels: chore, release:patch

#245 Better eloquent stubs
  stubs/BelongsTo.stubphp
  stubs/BelongsToMany.stubphp
  stubs/Collection.stubphp
  stubs/Container.stubphp
  stubs/EloquentBuilder.stubphp
  stubs/EloquentCollection.stubphp
  stubs/Enumerable.stubphp
  stubs/FactoryBuilder.stubphp
  stubs/HasMany.stubphp
  stubs/HasManyThrough.stubphp
  stubs/HasOne.stubphp
  stubs/HasOneOrMany.stubphp
  stubs/HasOneThrough.stubphp
  stubs/HasRelationships.stubphp
  stubs/InteractsWithInput.stubphp
  stubs/Model.stubphp
  stubs/MorphMany.stubphp
  stubs/MorphOne.stubphp
  stubs/MorphOneOrMany.stubphp
  stubs/MorphToMany.stubphp
  stubs/QueryBuilder.stubphp
  stubs/Relation.stubphp
Labels: release:feature, release:minor

#257 Improve testing experience
  tests/laravel-test.sh
  tests/lumen-test.sh
Labels: chore, release:patch

#267 Add more stubs for helpers
  stubs/helpers.stubphp
  tests/acceptance/Helpers.feature
Labels: release:feature, release:minor

#258 Automatically fix coding style issues
  .github/workflows/lint.yml
Labels: chore, release:patch

#252 Update dependencies, remove unused ones
  README.md
  composer.json
  phpcs.xml
  tests/Support/Module.php
  tests/acceptance/EloquentBuilderTypes.feature
  tests/acceptance/EloquentRelationTypes.feature
  tests/laravel-test.sh
Labels: chore, release:patch

#277 Name all unnamed test scenarios
  tests/acceptance/EloquentBuilderTypes.feature
  tests/acceptance/EloquentCollectionTypes.feature
  tests/acceptance/ExceptionHandler.feature
  tests/acceptance/RedirectReturnType.feature
  tests/acceptance/UrlReturnType.feature
Labels: release:internal

#278 Fix branch updater GitHub workflow
  .github/workflows/update-3x-branch.yml
Labels: release:internal

#279 Add stubs for `validator` and `view` helpers
  stubs/helpers.stubphp
Labels: release:feature, release:minor

#276 Add Pagination stubs
  src/Plugin.php
  stubs/BelongsToMany.stubphp
  stubs/Contracts/Pagination.stubphp
  stubs/HasManyThrough.stubphp
  stubs/Pagination.stubphp
  stubs/helpers.stubphp
  tests/acceptance/EloquentBuilderTypes.feature
  tests/acceptance/EloquentRelationTypes.feature
Labels: release:feature, release:minor

#283 Use View contract instead implementation
  src/Handlers/Helpers/ViewHandler.php
Labels: release:skip-changelog

#285 Remove Psalm 4 tests
  tests/acceptance/EloquentBuilderTypes.feature
Labels: release:skip-changelog

#275 Check for a parameter with nullable() in migrations
  src/Handlers/Eloquent/Schema/SchemaAggregator.php
Labels: release:fix, release:patch

#286 Support more helpers: auth, cache, dispatch, logs, rescue, to_route
  .github/workflows/test-laravel.yml
  .github/workflows/test.yml
  src/Handlers/Helpers/CacheHandler.php
  src/Plugin.php
  stubs/helpers.stubphp
  tests/acceptance/Helpers.feature
Labels: release:feature, release:minor

#289 Make auth()->check() calls readable by Psalm
  src/Fakes/FakeFilesystem.php
  stubs/helpers.stubphp
  tests/acceptance/Helpers.feature
Labels: release:fix

#290 Fix indentation
  .github/workflows/test.yml
Labels: release:skip-changelog

#292 Do not run auth() tests on Laravel <9.44
  tests/acceptance/Helpers.feature
Labels: release:skip-changelog

#272 [3.x] Eloquent Collection with templated keys
  src/Handlers/Eloquent/ModelRelationshipPropertyHandler.php
  stubs/BelongsToMany.stubphp
  stubs/Collection.stubphp
  stubs/EloquentBuilder.stubphp
  stubs/EloquentCollection.stubphp
  stubs/FactoryBuilder.stubphp
  stubs/HasManyThrough.stubphp
  stubs/HasOneOrMany.stubphp
  stubs/Model.stubphp
  stubs/Relation.stubphp
  tests/acceptance/CollectionTypes.feature
  tests/acceptance/EloquentBuilderTypes.feature
  tests/acceptance/EloquentCollectionTypes.feature
  tests/acceptance/EloquentRelationTypes.feature
Labels: release:feature, release:major

#296 Make plugin errors more verbose (add console output)
  docs/README.md
  src/Fakes/FakeModelsCommand.php
  src/Plugin.php
  src/Providers/ModelStubProvider.php
Labels: release:internal

#295 Better SchemaAggregator
  .github/workflows/test.yml
  .gitignore
  composer.json
  phpcs.xml
  phpunit.xml
  psalm.xml
  src/Handlers/Eloquent/Schema/SchemaAggregator.php
  tests/Unit/Handlers/Eloquent/Schema/AbstractSchemaAggregatorTest.php
  tests/Unit/Handlers/Eloquent/Schema/DefaultUserTableTest.php
  tests/Unit/Handlers/Eloquent/Schema/migrations/simple/2014_10_12_000000_create_users_table.php
Labels: release:minor

#302 Release drafter: allow manual run
  .github/workflows/release-drafter.yml
Labels: release:skip-changelog

#304 Error level 1 for codebase
  psalm-baseline.xml
  psalm.xml
  src/Fakes/FakeModelsCommand.php
  src/Handlers/Application/ContainerHandler.php
  src/Handlers/Application/OffsetHandler.php
  src/Handlers/Eloquent/Schema/SchemaAggregator.php
  src/Handlers/Eloquent/Schema/SchemaColumn.php
  src/Handlers/Helpers/PathHandler.php
  src/Plugin.php
  src/Providers/ApplicationInterfaceProvider.php
  src/Providers/ApplicationProvider.php
  src/Providers/FacadeStubProvider.php
  src/Providers/ModelStubProvider.php
  src/Util/ContainerResolver.php
  tests/acceptance/AbortIf.feature
Labels: release:internal

#306 Optimize property check
  src/Handlers/Eloquent/ModelMethodHandler.php
  src/Handlers/Eloquent/ModelPropertyAccessorHandler.php
  tests/Models/User.php
  tests/acceptance/EloquentModelPropertyTypes.feature
Labels: release:internal

#307 Fix stub extension
  stubs/Database/ManagesTransactions.stubphp
Labels: release:skip-changelog

#309 Improve return type detection for Laravel `path` helpers
  composer.json
  src/Handlers/Helpers/PathHandler.php
  src/Util/ContainerResolver.php
Labels: release:feature

#310 Cleanup testing module, reorganize stubs
  psalm.xml
  src/Plugin.php
  stubs/Contracts/Container.stubphp
  stubs/Database/BelongsTo.stubphp
  stubs/Database/BelongsToMany.stubphp
  stubs/Database/EloquentBuilder.stubphp
  stubs/Database/EloquentCollection.stubphp
  stubs/Database/FactoryBuilder.stubphp
  stubs/Database/HasMany.stubphp
  stubs/Database/HasManyThrough.stubphp
  stubs/Database/HasOne.stubphp
  stubs/Database/HasOneOrMany.stubphp
  stubs/Database/HasOneThrough.stubphp
  stubs/Database/HasRelationships.stubphp
  stubs/Database/Model.stubphp
  stubs/Database/MorphMany.stubphp
  stubs/Database/MorphOne.stubphp
  stubs/Database/MorphOneOrMany.stubphp
  stubs/Database/MorphToMany.stubphp
  stubs/Database/QueryBuilder.stubphp
  stubs/Database/Relation.stubphp
  stubs/Http/InteractsWithInput.stubphp
  stubs/Lumen/Application.stubphp
  stubs/Pagination/Pagination.stubphp
  stubs/Support/Collection.stubphp
  stubs/Support/DBFacade.stubphp
  stubs/Support/Enumerable.stubphp
  stubs/Support/Optional.stubphp
  tests/Support/Module.php
Labels: release:internal

#312 Support `throw_if` and `throw_unless`
  stubs/helpers.stubphp
  tests/acceptance/Helpers.feature
Labels: release:feature

#315 Update baseline for a new Laravel app
  tests/laravel-test-baseline.xml
Labels: release:skip-changelog
